### ISSUE TITLE
Feature Request: auto_expand for toc

### ISSUE THREAD

**Issue by Ray-Eldath** [ppoffice/hexo-component-inferno#10]
currently the toc generated for post will show all subtitles at once. for many long articles, this will leads to a full-page catalogue with many lines wrapped:
![image](https://user-images.githubusercontent.com/7938763/86505336-c4866280-bdf5-11ea-8b24-e243fcbdf0ae.png)
it wastes space while affecting user experience, for some substitles may be hidden forever provided the toc is still sticked. one decent solution is to make the toc stacked by default, but expended when the subtitle enters viewport:

![image](https://user-images.githubusercontent.com/7938763/86505390-889fcd00-bdf6-11ea-80ec-b419cc90e5af.png)

two popular hexo themes already bundled with such function AFAIK, related code is at [here](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/source/js/scroll.js) and [here](https://github.com/theme-next/hexo-theme-next/blob/18fb82bdfc/source/js/utils.js#L216-L294). I'm still investigating how to integrate such feature into icarus, hope the solution will be found out soon.

**Comment by ppoffice** [comment]
Feature added in https://github.com/ppoffice/hexo-component-inferno/releases/tag/0.6.0
