### ISSUE TITLE
Table of content don't recognize four-level subtitles

### ISSUE THREAD

**Issue by Ray-Eldath** [ppoffice/hexo-component-inferno#13]
This is the expected toc:
![image](https://user-images.githubusercontent.com/7938763/90750891-087ee980-e308-11ea-9868-4434f417dade.png)

but rendered into:
![image](https://user-images.githubusercontent.com/7938763/90750937-13d21500-e308-11ea-998c-d054c6c7a0ca.png)

obviously the adjacent three-level subtitle is not rendered. seems the [toc.jsx](https://github.com/ppoffice/hexo-component-inferno/blob/master/src/view/widget/toc.jsx) not process the four-level subtitles. it should either be rendered just as other subtitles, or completely ignored.

**Comment by ppoffice** [comment]
@Ray-Eldath ToC here only supports three levels of titles. Too many nested titles will make the lower-level titles unreadable.

**Comment by Ray-Eldath** [comment]
Sorry for the late response. I corrected my article, and it works fine now.
