### ISSUE TITLE
auto_expand should persist visibility between gaps of subtitles.

### ISSUE THREAD

**Issue by Ray-Eldath** [ppoffice/hexo-component-inferno#14]
toc:
![image](https://user-images.githubusercontent.com/7938763/90751991-6a8c1e80-e309-11ea-9c96-1cba3fb9542a.png)

GIF:
![gif](https://user-images.githubusercontent.com/7938763/90752019-711a9600-e309-11ea-8dfa-1752ef79030f.gif)

The problem is that when the viewport is scrolled into the three-level subtitles, the whole toc is stacked abruptly. Notably, this bug only happens in the first sequence of three-level subtitles but works fine at the second occurance of three-level subtitle. IMHO this is because the first and second three-level subtitles is directly under the first-level subtitle, namely there's a "gap" between its direct upper level and itself (1 down to 3, 2 is missed). when such gap perceived, the expected behavior, arguably, is to persist the visibility of the toc.

**Comment by ppoffice** [comment]
@Ray-Eldath By definition, third-level titles should sit under second-levels. There is little ToC can do to accommodate such title arrangement.
