### ISSUE TITLE
TOC 功能新增

### ISSUE THREAD

**Issue by zapzqc** [ppoffice/hexo-component-inferno#15]
现在的toc三级以后的无法展开了...最好是能够看到所有层级，哪怕规定最多6级也可以。

还有就是能否加一个默认toc展开的选项，这样看起来会方便些。

**Comment by ppoffice** [comment]
@zapzqc 在你的ToC配置中添加如下行：

```diff
     -
         # Where should the widget be placed, left sidebar or right sidebar
         position: left
         type: toc
         # Whether to show the index of each heading
         index: true
+        # Whether to collapse sub-headings when they are out-of-view
+        collapsed: true # 设置为false时强制展开所有标题
+        # Maximum level of headings to show (1-6)
+        depth: 3 # 最多展示的标题级数（1-6）
```

**Comment by zapzqc** [comment]
> @zapzqc 在你的ToC配置中添加如下行：
> 
> ```diff
>      -
>          # Where should the widget be placed, left sidebar or right sidebar
>          position: left
>          type: toc
>          # Whether to show the index of each heading
>          index: true
> +        # Whether to collapse sub-headings when they are out-of-view
> +        collapsed: true # 设置为false时强制展开所有标题
> +        # Maximum level of headings to show (1-6)
> +        depth: 3 # 最多展示的标题级数（1-6）
> ```

第一时间更新，没问题了，感谢～～

再提个建议，如果默认是展开的情况，点击toc，是否可以把点击的那项折叠起来，再点再展开。
