### ISSUE TITLE
show hostname of links widget only there're enough space w/o wrap the line

### ISSUE THREAD

**Issue by Ray-Eldath** [ppoffice/hexo-component-inferno#17]
Currently the *links* widget defaultly show all hostname. despite the situation where the description is long, and the item will wrap, causing *very uncomforable looking*, e.g.
![image](https://user-images.githubusercontent.com/7938763/107918990-95e48300-6fa5-11eb-8e79-1275b85b4440.png)

and it's better to automatically discard the hostname part if there's no enough space. this could be archive by reimplement the structure in `hexo-component-inferno → lib → view → widget → link.js → Links → <function> → value`, using a grid system or whatnot.

currently I'm using hand-written and hard-coded length-of-string schema, kinda like this:
```javascript
let item = [(0, _inferno.createVNode)(1, "span", "level-left", (0, _inferno.createVNode)(1, "span", "level-item", i, 0), 2)];
if (hostname.length <= 15)
  item.push((0, _inferno.createVNode)(1, "span", "level-right", (0, _inferno.createVNode)(1, "span", "level-item tag", hostname, 0), 2));
return (0, _inferno.createVNode)(1, "li", null, (0, _inferno.createVNode)(1, "a", "level is-mobile", item, ...
```
Considering the fact that this is a relatively very small, simple but great improvement, it'll be better if this small improvement could be merged into mainstream, and released ASAP.

**Comment by ppoffice** [comment]
Thank you for the advice. It's probably better to give the user an option to hide domain name labels, since you never know how long the domain name or path will be.

**Comment by Ray-Eldath** [comment]
currently I'm working on this feature (and another very small improvement), and they're both absolutely backward-compatible. I'll propose a PR once I finish it. 😉
