### ISSUE TITLE
Structured data missing "publisher"

### ISSUE THREAD

**Issue by markleetw** [ppoffice/hexo-component-inferno#19]
![image](https://user-images.githubusercontent.com/11422478/108463711-d3a11e80-72b9-11eb-9b41-65746e9c9b87.png)

Currently I validate my post which is using hexo-theme-icarus. 
I notice that the google structured data validator report that the post doesn't have the required column named "publisher".
I think we could probably just add "publisher" into strutured data like "author".

**Comment by ppoffice** [comment]
#20
