### ISSUE TITLE
How to move widget adsense to hexo's theme folder?

### ISSUE THREAD

**Issue by nxkun** [ppoffice/hexo-component-inferno#22]
Is it posible to move widget adsense from hexo-component-inferno to local theme forlder? I mean in this folder "/hexo/themes/icarus/layout/widget/"

**Comment by ppoffice** [comment]
Yes you can. Please see `Where are the layout files for widgets/comments/share...? How do I customize built-in widgets/comments/share...?` at https://ppoffice.github.io/hexo-theme-icarus/uncategorized/faq/#Layout

**Comment by nxkun** [comment]
Thanks a lot I'll try it.
