### ISSUE TITLE
希望作者把twikoo评论添加进去！

### ISSUE THREAD

**Issue by HanMoe** [ppoffice/hexo-component-inferno#23]

**Comment by OldChenGit** [comment]
求大佬解决啊!怎么配置进去。

**Comment by ppoffice** [comment]
@OldChenGit It seems that twikoo only deploys to Tencent cloud right now but Tencent recently removed the free tier plan. I will consider following up when it supports other cloud functions that is more friendly to developers outside of China, or when it supports self-host.

https://github.com/imaegoo/twikoo/issues/163

**Comment by ppoffice** [comment]
#44
