### ISSUE TITLE
Update KaTeX to 1.15.1

### ISSUE THREAD

**Issue by atlanswer** [ppoffice/hexo-component-inferno#31]
https://github.com/ppoffice/hexo-component-inferno/blob/a8ffee270cd9f7c88d97261d67d0bc08e9494043/src/view/plugin/katex.jsx#L59-L62

Changelog: https://github.com/KaTeX/KaTeX/releases

Feature added: `\relax`, `\nonumber` and `\notag` were implemented.

Would you mind making a new release? The npm package hasn't been updated for 5 months. The `katex` plugin was still v0.11.1 and every new feature since then like `align` environment was not available.

**Comment by ppoffice** [comment]
[hexo-component-inferno@0.14.0](https://github.com/ppoffice/hexo-component-inferno/releases/tag/0.14.0) is released.
