### ISSUE TITLE
Disable download icon

### ISSUE THREAD

**Issue by punksinatra** [ppoffice/hexo-component-inferno#38]
Lightgallery has the option to disable the download icon when viewing photos from the gallery but I can seem to find it. 

Can anyone point me to the right direction? Thanks

**Comment by ppoffice** [comment]
@punksinatra You may add `download: false` to this line:

https://github.com/ppoffice/hexo-component-inferno/blob/1.1.0/src/view/plugin/gallery.jsx#L39
