### ISSUE TITLE
External Links bug, unable to render url AND hide hostname with Icarus

### ISSUE THREAD

**Issue by vishvish** [ppoffice/hexo-component-inferno#58]
Based on docs found here: https://ppoffice.github.io/hexo-component-inferno/module-view_widget_links-Links.html

Using the following YAML in _config.icarus.yml

```
	links:
      Link Name 1: /path/to/external/site
      Link Name 2:
        link: /path/to/external/site
        hide_hostname: true
```

The first link renders correctly.

The second link displays the name, and hides the space for the hostname, but does not render the hostname within the link so there is no link.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/184423/219818412-78a9d3a9-7bd7-4946-a7c2-66a3eb3b2980.png">

**Comment by ppoffice** [comment]
I don't see a problem here. Hide hostname means that it will not be rendered.

**Comment by vishvish** [comment]
The URL link doesn't work - it's not rendering the hostname URL within the link `<a href="xxx>`

**Comment by ppoffice** [comment]
@vishvish Thank you for pointing it out. The bug is fixed in the latest commit.

**Comment by vishvish** [comment]
Awesome, thanks @ppoffice - I tried to find the bug and patch my own library, bit couldn't!
