### ISSUE TITLE
如何自己扩展新的组件？ 

### ISSUE THREAD

**Issue by abel533** [ppoffice/hexo-component-inferno#68]
我参考Profile写了一个实现，使用的时候总是报错，能否说一下扩展widget的方法？

**Comment by abel533** [comment]
在`/theme/icarus/layout/widget/` 下面创建即可，发现可以直接像node.js一样debug时，解决问题就简单多了。

**Comment by AGEN233** [comment]
麻烦问一下部件的js文件如何引入和调用呢，把js连带html的实现写在/theme/icarus/layout/widget/ .jsx可行吗
